# Strongly encouraged to use this option to decrease gain factor in STUN
# binding responses.
response-origin-only-with-rfc5780

# Use your desired port (3478 is standard)
listening-port=3478

# If you want to use TLS (recommended for TURN over TLS)
# listening-ip=<your_public_ip>
# tls-listening-port=5349

external-ip=134.209.220.119
listening-ip=134.209.220.119

# Realm can be any string (used for authentication)
realm=rc-tank

# Set a static user for testing (username:password)
user=tank:tankpass

# Enable long-term credentials mechanism
lt-cred-mech 

# Allow traffic from anywhere (for tests)
# (You may want to restrict this in production)
fingerprint